polaris.persistence.type=relational-jdbc
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/polaris
quarkus.datasource.username=admin
quarkus.datasource.password=admin123
quarkus.datasource.devservices.enabled=false
